title: BSides Oslo 2025
description: October 30th at Vulkan Area. CFP is accepting submissions.
event:
  location: Vulkan Arena
  time: 30 October 2025 

show_buttons: true
buttons:
 - text: Tickets
   url: https://www.letsreg.com/no/event/bsidesoslo2025
 - text: Sponsor information
   url: /pages/SponsorPrimer

# Social media links
socials:
- id: youtube
  svg: youtube
  url: https://www.youtube.com/bsidesoslo
- id: mastadon
  svg: mastadon
  url: https://infosec.exchange/@bsidesoslo
- id: bluesky
  svg: bsky
  url: https://bsky.app/profile/bsidesoslo.no
- id: linkedin
  svg: linkedin
  url: https://www.linkedin.com/company/bsidesoslo
- id: twitter
  svg: twitter
  url: https://twitter.com/oslobsides
- id: email
  svg: letter
  url: mailto:info@bsidesoslo.no 

# Website stuff
exclude: 
 - .sass-cache/
 - .jekyll-cache/
 - gemfiles/
 - Gemfile
 - Gemfile.lock
 - node_modules/
 - vendor/*
 - CODE_OF_CONDUCT.md
 - LICENSE
 - README.md
 - .devcontainers
